// <auto-generated />
using System;
using Itam.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Itam.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806091328_AllowUnassignedStorage")]
    partial class AllowUnassignedStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Itam.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("Assets", (string)null);

                    b.HasDiscriminator<int>("AssetType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Itam.Domain.Entities.AssetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("AssetId", "UnassignedAt")
                        .IsUnique()
                        .HasFilter("[UnassignedAt] IS NULL");

                    b.ToTable("AssetAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssetAssignments_UnassignedAfterAssigned", "[UnassignedAt] IS NULL OR [UnassignedAt] >= [AssignedAt]");
                        });
                });

            modelBuilder.Entity("Itam.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("RepairHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("RepairHistoryId");

                    b.HasIndex("TicketId");

                    b.ToTable("Attachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attachments_FileSize", "[FileSize] > 0");

                            t.HasCheckConstraint("CK_Attachments_SingleOwner", "(CASE WHEN [TicketId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [RepairHistoryId] IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN [AssetId] IS NOT NULL THEN 1 ELSE 0 END) = 1");
                        });
                });

            modelBuilder.Entity("Itam.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReasonRevoked")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Itam.Domain.Entities.RepairHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RepairDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepairDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("AssetId");

                    b.HasIndex("TicketId");

                    b.ToTable("RepairHistories", (string)null);
                });

            modelBuilder.Entity("Itam.Domain.Entities.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DesktopPcId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PcId");

                    b.Property<Guid?>("LaptopId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StorageType")
                        .HasColumnType("int");

                    b.Property<int>("StorageUnit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DesktopPcId");

                    b.HasIndex("LaptopId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("StorageDevices", null, t =>
                        {
                            t.HasCheckConstraint("CK_StorageDevices_Capacity", "[Capacity] > 0");

                            t.HasCheckConstraint("CK_StorageDevices_ExclusiveOwner", "NOT ([LaptopId] IS NOT NULL AND [PcId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Itam.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Priority");

                    b.HasIndex("Status");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Itam.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Itam.Domain.Entities.DesktopPc", b =>
                {
                    b.HasBaseType("Itam.Domain.Entities.Asset");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Itam.Domain.Entities.Dock", b =>
                {
                    b.HasBaseType("Itam.Domain.Entities.Asset");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Dock_Brand");
                        });

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Itam.Domain.Entities.KeyboardMouseSet", b =>
                {
                    b.HasBaseType("Itam.Domain.Entities.Asset");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ConnectionType")
                        .HasColumnType("int");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("KeyboardMouseSet_Brand");
                        });

                    b.HasDiscriminator().HasValue(4);
                });

            modelBuilder.Entity("Itam.Domain.Entities.Laptop", b =>
                {
                    b.HasBaseType("Itam.Domain.Entities.Asset");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CPU")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GPU")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Laptop_Brand");

                            t.Property("CPU")
                                .HasColumnName("Laptop_CPU");

                            t.Property("GPU")
                                .HasColumnName("Laptop_GPU");

                            t.Property("Model")
                                .HasColumnName("Laptop_Model");

                            t.Property("RAM")
                                .HasColumnName("Laptop_RAM");

                            t.Property("SerialNumber")
                                .HasColumnName("Laptop_SerialNumber");
                        });

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Itam.Domain.Entities.Monitor", b =>
                {
                    b.HasBaseType("Itam.Domain.Entities.Asset");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RefreshRate")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Size")
                        .HasColumnType("float");

                    b.ToTable("Assets", t =>
                        {
                            t.Property("Brand")
                                .HasColumnName("Monitor_Brand");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Itam.Domain.Entities.AssetAssignment", b =>
                {
                    b.HasOne("Itam.Domain.Entities.Asset", "Asset")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Itam.Domain.Entities.User", "Employee")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Itam.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Itam.Domain.Entities.Asset", "Asset")
                        .WithMany("Attachments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Itam.Domain.Entities.RepairHistory", "RepairHistory")
                        .WithMany("Attachments")
                        .HasForeignKey("RepairHistoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Itam.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("RepairHistory");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Itam.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Itam.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Itam.Domain.Entities.RepairHistory", b =>
                {
                    b.HasOne("Itam.Domain.Entities.User", "Admin")
                        .WithMany("RepairHistories")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Itam.Domain.Entities.Asset", "Asset")
                        .WithMany("RepairHistories")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Itam.Domain.Entities.Ticket", "Ticket")
                        .WithMany("RepairHistories")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Asset");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Itam.Domain.Entities.Storage", b =>
                {
                    b.HasOne("Itam.Domain.Entities.DesktopPc", "DesktopPc")
                        .WithMany("StorageDevices")
                        .HasForeignKey("DesktopPcId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Itam.Domain.Entities.Laptop", "Laptop")
                        .WithMany("StorageDevices")
                        .HasForeignKey("LaptopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DesktopPc");

                    b.Navigation("Laptop");
                });

            modelBuilder.Entity("Itam.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Itam.Domain.Entities.Asset", "Asset")
                        .WithMany("Tickets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Itam.Domain.Entities.User", "Employee")
                        .WithMany("Tickets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Itam.Domain.Entities.Asset", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("Attachments");

                    b.Navigation("RepairHistories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Itam.Domain.Entities.RepairHistory", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Itam.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("RepairHistories");
                });

            modelBuilder.Entity("Itam.Domain.Entities.User", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("RepairHistories");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Itam.Domain.Entities.DesktopPc", b =>
                {
                    b.Navigation("StorageDevices");
                });

            modelBuilder.Entity("Itam.Domain.Entities.Laptop", b =>
                {
                    b.Navigation("StorageDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
